//FIX: CAMERA2D ORTHO
//FIX: CAMERA2D CHECK IF DIRTY FOR EACH TRANSFORM COMPONENT AND THEN CHANGE AND MULTIPLY THE CAMERA MATRIX
//FIX: ^^^^ SAME FOR THE TRANSFORM COMPONENT IN COMPONENTS FILE FOR EACH ENTITY ^^^^
//SOKOL_AUDIO FOR AUDIO