#pragma once

#define DARK_MOUSE_BUTTON_1         0
#define DARK_MOUSE_BUTTON_2         1
#define DARK_MOUSE_BUTTON_3         2
#define DARK_MOUSE_BUTTON_4         3
#define DARK_MOUSE_BUTTON_5         4
#define DARK_MOUSE_BUTTON_6         5
#define DARK_MOUSE_BUTTON_7         6
#define DARK_MOUSE_BUTTON_8         7
#define DARK_MOUSE_BUTTON_LAST      DARK_MOUSE_BUTTON_8
#define DARK_MOUSE_BUTTON_LEFT      DARK_MOUSE_BUTTON_1
#define DARK_MOUSE_BUTTON_RIGHT     DARK_MOUSE_BUTTON_2
#define DARK_MOUSE_BUTTON_MIDDLE    DARK_MOUSE_BUTTON_3